# Generated by Django 6.0 on 2025-12-26 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('MP', 'Matéria-Prima'), ('PA', 'Produto Acabado')], default='MP', max_length=2, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('MT', 'Metro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('LT', 'Litro'), ('CX', 'Caixa'), ('PCT', 'Pacote')], default='UN', max_length=10, verbose_name='Unidade de Medida')),
                ('preco_custo_medio', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Preço Custo Médio')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Estoque Mínimo')),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Estoque Atual')),
                ('url_foto', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL Foto')),
                ('status_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'db_table': 'itens',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mov', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Total')),
                ('documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Documento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_mov', models.DateTimeField(auto_now_add=True, verbose_name='Data Movimentação')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'db_table': 'estoque_movimentacoes',
                'ordering': ['-data_mov'],
            },
        ),
    ]
