# Generated by Django 6.0 on 2025-12-30 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_pessoa_celular_remove_pessoa_rg_ie_and_more'),
        ('estoque', '0009_create_locais_destinos'),
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('permite_saldo_negativo', models.BooleanField(default=False, help_text='Se marcado, permite saídas mesmo sem saldo suficiente', verbose_name='Permite Saldo Negativo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Local de Estoque',
                'verbose_name_plural': 'Locais de Estoque',
                'db_table': 'locais_estoque',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste/Inventário'), ('ESTORNO', 'Estorno')], db_index=True, max_length=20, verbose_name='Tipo de Movimento')),
                ('documento', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Nº Documento')),
                ('documento_tipo', models.CharField(blank=True, choices=[('NF', 'Nota Fiscal'), ('REQ', 'Requisição'), ('OP', 'Ordem de Produção'), ('INV', 'Inventário'), ('DEV', 'Devolução'), ('TRF', 'Transferência'), ('OUT', 'Outros')], max_length=10, null=True, verbose_name='Tipo Documento')),
                ('data_movimento', models.DateTimeField(db_index=True, verbose_name='Data/Hora do Movimento')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0.0, help_text='Custo na entrada ou custo médio na saída', max_digits=12, verbose_name='Custo Unitário')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Custo Total')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'db_table': 'movimentos_estoque',
                'ordering': ['-data_movimento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_op', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Nº OP')),
                ('quantidade_planejada', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade Planejada')),
                ('quantidade_produzida', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Quantidade Produzida')),
                ('data_planejada', models.DateField(verbose_name='Data Planejada')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data Fim')),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('LIBERADA', 'Liberada'), ('EM_PRODUCAO', 'Em Produção'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PLANEJADA', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
                'db_table': 'ordens_producao',
                'ordering': ['-numero_op'],
            },
        ),
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Quantidade')),
                ('custo_medio', models.DecimalField(decimal_places=4, default=0.0, help_text='Weighted Average Cost', max_digits=12, verbose_name='Custo Médio (WAC)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Saldo de Estoque',
                'verbose_name_plural': 'Saldos de Estoque',
                'db_table': 'saldos_estoque',
            },
        ),
        migrations.RemoveField(
            model_name='estoquemovimentacao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='estoquemovimentacao',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='estoque_atual',
        ),
        migrations.RemoveField(
            model_name='item',
            name='preco_custo_medio',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status_ativo',
        ),
        migrations.AddField(
            model_name='item',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='item',
            name='codigo',
            field=models.CharField(db_index=True, default='AUTO', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='item',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='item',
            name='estoque_maximo',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=12, null=True, verbose_name='Estoque Máximo'),
        ),
        migrations.AddField(
            model_name='item',
            name='ncm',
            field=models.CharField(blank=True, help_text='Nomenclatura Comum do Mercosul', max_length=20, null=True, verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo_item',
            field=models.CharField(choices=[('MP', 'Matéria-Prima'), ('PA', 'Produto Acabado'), ('SEMI', 'Semi-Acabado'), ('CONSUMIVEL', 'Consumível')], db_index=True, default='MP', max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('MT', 'Metro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('LT', 'Litro'), ('CX', 'Caixa'), ('PCT', 'Pacote'), ('PC', 'Peça'), ('BAR', 'Barra'), ('CHAPA', 'Chapa')], default='UN', max_length=10, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url_foto',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Foto'),
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(default='1.0', max_length=20, verbose_name='Versão')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_vigencia', models.DateField(verbose_name='Data Vigência')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('produto', models.ForeignKey(limit_choices_to={'tipo_item__in': ['PA', 'SEMI']}, on_delete=django.db.models.deletion.CASCADE, related_name='bom_produto', to='estoque.item', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'BOM (Lista de Materiais)',
                'verbose_name_plural': 'BOMs (Listas de Materiais)',
                'db_table': 'bom',
                'ordering': ['produto', '-versao'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Quantidade necessária para produzir 1 unidade do produto', max_digits=12, verbose_name='Quantidade')),
                ('sequencia', models.IntegerField(default=0, verbose_name='Sequência')),
                ('percentual_perda', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de perda no processo', max_digits=5, verbose_name='% Perda')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.bom', verbose_name='BOM')),
                ('item_componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_componente', to='estoque.item', verbose_name='Item Componente')),
            ],
            options={
                'verbose_name': 'Item da BOM',
                'verbose_name_plural': 'Itens da BOM',
                'db_table': 'bom_itens',
                'ordering': ['bom', 'sequencia'],
            },
        ),
        migrations.CreateModel(
            name='DestinoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('PRODUCAO', 'Produção'), ('PROJETO', 'Projeto/Obra'), ('LOJA', 'Loja/Pronta Entrega'), ('MANUTENCAO', 'Manutenção'), ('AMOSTRA', 'Amostra'), ('PERDA', 'Perda/Sucata'), ('DEVOLUCAO', 'Devolução'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('controla_custo', models.BooleanField(default=True, help_text='Se marcado, o custo será lançado no destino (projeto, etc)', verbose_name='Controla Custo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Destino de Estoque',
                'verbose_name_plural': 'Destinos de Estoque',
                'db_table': 'destinos_estoque',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='GrupoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_item_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Grupo de Item',
                'verbose_name_plural': 'Grupos de Itens',
                'db_table': 'grupos_item',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='estoque.grupoitem', verbose_name='Grupo'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['codigo'], name='itens_codigo_82b43d_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['descricao'], name='itens_descric_fe9d04_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tipo_item'], name='itens_tipo_it_9de79e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['ativo'], name='itens_ativo_2611ae_idx'),
        ),
        migrations.AddField(
            model_name='localestoque',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='localestoque',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='destino',
            field=models.ForeignKey(blank=True, help_text='Finalidade da saída', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='estoque.destinoestoque', verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_pessoa__fornecedor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to='cadastros.pessoa', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='estoque.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='local_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_destino', to='estoque.localestoque', verbose_name='Local Destino'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='local_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_origem', to='estoque.localestoque', verbose_name='Local Origem'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='movimento_estornado',
            field=models.ForeignKey(blank=True, help_text='Referência ao movimento que está sendo estornado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos', to='estoque.movimentoestoque', verbose_name='Movimento Estornado'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to='projetos.projeto', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao', to='estoque.bom', verbose_name='BOM'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='local_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao_destino', to='estoque.localestoque', verbose_name='Local Destino Produto'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='local_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao_origem', to='estoque.localestoque', verbose_name='Local Produção'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='produto',
            field=models.ForeignKey(limit_choices_to={'tipo_item__in': ['PA', 'SEMI']}, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao', to='estoque.item', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_producao', to='projetos.projeto', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='saldoestoque',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='estoque.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='saldoestoque',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='estoque.localestoque', verbose_name='Local'),
        ),
    ]
