# Generated by Django 6.0 on 2025-12-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_localestoque_movimentoestoque_ordemproducao_and_more'),
        ('projetos', '0002_alter_alocacaoprojeto_movimentacao_estoque_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstoqueMovimentacao',
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('produto', 'versao')},
        ),
        migrations.AlterUniqueTogether(
            name='bomitem',
            unique_together={('bom', 'item_componente')},
        ),
        migrations.AddIndex(
            model_name='destinoestoque',
            index=models.Index(fields=['codigo'], name='destinos_es_codigo_82df61_idx'),
        ),
        migrations.AddIndex(
            model_name='destinoestoque',
            index=models.Index(fields=['tipo'], name='destinos_es_tipo_af9dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoitem',
            index=models.Index(fields=['codigo'], name='grupos_item_codigo_580ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='localestoque',
            index=models.Index(fields=['codigo'], name='locais_esto_codigo_d4e192_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['tipo_movimento'], name='movimentos__tipo_mo_2da57d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['data_movimento'], name='movimentos__data_mo_b1146c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['documento'], name='movimentos__documen_584e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['item'], name='movimentos__item_id_155b67_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['local_origem'], name='movimentos__local_o_7ffafa_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['local_destino'], name='movimentos__local_d_ebbe92_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['projeto'], name='movimentos__projeto_e8ca24_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['-data_movimento'], name='movimentos__data_mo_5d4e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemproducao',
            index=models.Index(fields=['numero_op'], name='ordens_prod_numero__acefd4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemproducao',
            index=models.Index(fields=['status'], name='ordens_prod_status_cf85ea_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemproducao',
            index=models.Index(fields=['data_planejada'], name='ordens_prod_data_pl_f3b5e0_idx'),
        ),
        migrations.AddIndex(
            model_name='saldoestoque',
            index=models.Index(fields=['item', 'local'], name='saldos_esto_item_id_00a414_idx'),
        ),
        migrations.AddIndex(
            model_name='saldoestoque',
            index=models.Index(fields=['item'], name='saldos_esto_item_id_64331d_idx'),
        ),
        migrations.AddIndex(
            model_name='saldoestoque',
            index=models.Index(fields=['local'], name='saldos_esto_local_i_c81016_idx'),
        ),
        migrations.AddIndex(
            model_name='saldoestoque',
            index=models.Index(fields=['quantidade'], name='saldos_esto_quantid_b82ac4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saldoestoque',
            unique_together={('item', 'local')},
        ),
    ]
