# Generated by Django 6.0 on 2025-12-30 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_delete_estoquemovimentacao_alter_bom_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Quantidade')),
                ('custo_medio', models.DecimalField(decimal_places=4, default=0.0, help_text='Weighted Average Cost', max_digits=12, verbose_name='Custo Médio (WAC)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='estoque.item', verbose_name='Item')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='estoque.localestoque', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Saldo de Estoque',
                'verbose_name_plural': 'Saldos de Estoque',
                'db_table': 'saldos_estoque',
            },
        ),
        migrations.AddIndex(
            model_name='saldoestoque',
            index=models.Index(fields=['item', 'local'], name='saldos_esto_item_id_4e6f19_idx'),
        ),
        migrations.AddIndex(
            model_name='saldoestoque',
            index=models.Index(fields=['item'], name='saldos_esto_item_id_3a5c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='saldoestoque',
            index=models.Index(fields=['local'], name='saldos_esto_local_i_2f1a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='saldoestoque',
            index=models.Index(fields=['quantidade'], name='saldos_esto_quantid_7b2e4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saldoestoque',
            unique_together={('item', 'local')},
        ),
    ]
