# Generated by Django 6.0 on 2026-01-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_criar_saldos_estoque'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='saldoestoque',
            new_name='saldos_esto_item_id_00a414_idx',
            old_name='saldos_esto_item_id_4e6f19_idx',
        ),
        migrations.RenameIndex(
            model_name='saldoestoque',
            new_name='saldos_esto_item_id_64331d_idx',
            old_name='saldos_esto_item_id_3a5c8b_idx',
        ),
        migrations.RenameIndex(
            model_name='saldoestoque',
            new_name='saldos_esto_local_i_c81016_idx',
            old_name='saldos_esto_local_i_2f1a9e_idx',
        ),
        migrations.RenameIndex(
            model_name='saldoestoque',
            new_name='saldos_esto_quantid_b82ac4_idx',
            old_name='saldos_esto_quantid_7b2e4d_idx',
        ),
    ]
