# Generated by Django 6.0 on 2026-01-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_rename_saldos_esto_item_id_4e6f19_idx_saldos_esto_item_id_00a414_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, choices=[('ALUMINIO', 'Alumínio'), ('FERRO', 'Ferro'), ('ACO', 'Aço'), ('VIDRO', 'Vidro'), ('MADEIRA', 'Madeira'), ('PLASTICO', 'Plástico'), ('BORRACHA', 'Borracha'), ('OUTROS', 'Outros')], max_length=20, null=True, verbose_name='Material'),
        ),
    ]
