# Generated by Django 6.0 on 2026-01-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_item_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, help_text='Imagem do item', null=True, upload_to='estoque/itens/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url_foto',
            field=models.CharField(blank=True, help_text='Alternativa: URL externa da foto', max_length=500, null=True, verbose_name='URL Foto'),
        ),
    ]
