# Generated by Django 6.0 on 2026-01-03 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_rename_pessoa_emp_ativo_idx_cadastros_p_empresa_b3572f_idx_and_more'),
        ('estoque', '0015_item_foto_alter_item_url_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoque',
            name='liberado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_liberados', to=settings.AUTH_USER_MODEL, verbose_name='Liberado Por'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='solicitante_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_solicitados', to='cadastros.pessoa', verbose_name='Quem Solicitou o Material'),
        ),
    ]
