# Generated by Django 6.0 on 2026-02-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_movimentoestoque_liberado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status_ativo',
            field=models.BooleanField(default=True, verbose_name='Status Ativo'),
        ),
    ]
