# Generated by Django 6.0 on 2025-12-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='rg_ie',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='site',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='celular1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular 1'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='celular2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular 2'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cnh_categoria',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=6, null=True, verbose_name='Categoria CNH'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ctps',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CTPS'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Admissão'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_demissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Demissão'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_emissao_rg',
            field=models.DateField(blank=True, null=True, verbose_name='Data Emissão RG'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_expedicao_ctps',
            field=models.DateField(blank=True, null=True, verbose_name='Data Expedição CTPS'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='deficiencia',
            field=models.BooleanField(default=False, verbose_name='Possui Deficiência'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='descricao_ramo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição do Ramo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('fundamental_incompleto', 'Fundamental Incompleto'), ('fundamental_completo', 'Fundamental Completo'), ('medio_incompleto', 'Médio Incompleto'), ('medio_completo', 'Médio Completo'), ('superior_incompleto', 'Superior Incompleto'), ('superior_completo', 'Superior Completo'), ('pos_graduacao', 'Pós-Graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=50, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='orgao_emissor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Emissor'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ramo_atividade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ramo de Atividade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='secao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Seção'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='serie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Série CTPS'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='terceiro',
            field=models.BooleanField(default=False, verbose_name='É Terceiro'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='titulo_eleitoral',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Título de Eleitor'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='uf_ctps',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF CTPS'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='zona',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade'),
        ),
    ]
