# Generated by Django 6.0 on 2025-12-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_pessoa_celular_remove_pessoa_rg_ie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='vendedor',
            field=models.BooleanField(default=False, verbose_name='É Vendedor'),
        ),
    ]
