# Generated by Django 6.0 on 2026-01-02 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_adicionar_campo_vendedor'),
        ('cadastros', '0005_empresa_required'),
    ]

    operations = [
    ]
