# Generated by Django 6.0 on 2026-01-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_merge_20260101_2120'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pessoa',
            new_name='cadastros_p_empresa_b3572f_idx',
            old_name='pessoa_emp_ativo_idx',
        ),
        migrations.RenameIndex(
            model_name='pessoa',
            new_name='cadastros_p_empresa_42e4a0_idx',
            old_name='pessoa_emp_cliente_idx',
        ),
        migrations.RenameIndex(
            model_name='pessoa',
            new_name='cadastros_p_empresa_9b4d77_idx',
            old_name='pessoa_emp_fornec_idx',
        ),
        migrations.RenameIndex(
            model_name='pessoa',
            new_name='cadastros_p_cpf_cnp_6b322a_idx',
            old_name='pessoa_cpf_cnpj_idx',
        ),
        migrations.RenameIndex(
            model_name='produto',
            new_name='cadastros_p_empresa_43c22f_idx',
            old_name='produto_emp_ativo_idx',
        ),
        migrations.RenameIndex(
            model_name='produto',
            new_name='cadastros_p_empresa_eff5bd_idx',
            old_name='produto_emp_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='produto',
            new_name='cadastros_p_codigo_ccbacc_idx',
            old_name='produto_codigo_idx',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf_cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
    ]
