# Generated by Django 6.0.1 on 2026-03-09 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_pessoa_data_nascimento_pessoa_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail 2'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo_pix',
            field=models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'E-mail'), ('TELEFONE', 'Telefone'), ('ALEATORIA', 'Chave Aleatória')], max_length=10, null=True, verbose_name='Tipo de Chave PIX'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Vincular esta pessoa a um usuário do sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema'),
        ),
    ]
