# Generated by Django 6.0.1 on 2026-03-09 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_pessoa_chave_pix_pessoa_email2_pessoa_tipo_pix_and_more'),
        ('financeiro', '0014_alter_centrocusto_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='agencia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.banco', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta'),
        ),
    ]
