# Generated by Django 6.0.1 on 2026-03-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_pessoa_agencia_pessoa_banco_pessoa_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto_funcionario',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/fotos/', verbose_name='Foto do Funcionário'),
        ),
    ]
