# Generated by Django 6.0 on 2025-12-30 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_localestoque_movimentoestoque_ordemproducao_and_more'),
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacaoprojeto',
            name='movimentacao_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.movimentoestoque', verbose_name='Movimentação Estoque'),
        ),
        migrations.AlterField(
            model_name='contacorrenteprojeto',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_corrente_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='vendadiretaitem',
            name='movimentacao_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.movimentoestoque', verbose_name='Movimentação Estoque'),
        ),
    ]
