# Generated by Django 6.0 on 2025-12-30 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_pessoa_celular_remove_pessoa_rg_ie_and_more'),
        ('projetos', '0002_alter_alocacaoprojeto_movimentacao_estoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacaoprojeto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'fornecedor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_fornecimento', to='cadastros.pessoa', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='alocacaoprojeto',
            name='funcionario',
            field=models.ForeignKey(blank=True, limit_choices_to={'funcionario': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_trabalho', to='cadastros.pessoa', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'cliente': True}, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='cadastros.pessoa', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'cliente': True}, on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='cadastros.pessoa', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='vendadireta',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'cliente': True}, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='cadastros.pessoa', verbose_name='Cliente'),
        ),
    ]
