# Generated by Django 6.0 on 2025-12-30 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_adicionar_campo_vendedor'),
        ('projetos', '0003_corrigir_limit_choices_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'vendedor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_vendedor', to='cadastros.pessoa', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'vendedor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='projetos_vendedor', to='cadastros.pessoa', verbose_name='Vendedor/Responsável'),
        ),
    ]
