# Generated by Django 6.0 on 2025-12-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alterar_vendedor_para_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoitem',
            name='tipo',
            field=models.CharField(choices=[('PRODUTO', 'Produto'), ('MATERIAL', 'Material'), ('SERVICO', 'Serviço'), ('MAO_OBRA', 'Mão de Obra')], default='PRODUTO', max_length=20, verbose_name='Tipo'),
        ),
    ]
