# Generated by Django 6.0 on 2025-12-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_alter_orcamentoitem_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('A_VISTA', 'À Vista'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência Bancária'), ('PARCELADO', 'Parcelado'), ('CHEQUE', 'Cheque')], default='A_VISTA', max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
