# Generated by Django 6.0 on 2025-12-30 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_orcamento_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='numero_parcelas',
            field=models.IntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor pago como entrada (opcional)', max_digits=12, verbose_name='Valor de Entrada'),
        ),
        migrations.CreateModel(
            name='OrcamentoParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField(verbose_name='Número da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='projetos.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Parcela do Orçamento',
                'verbose_name_plural': 'Parcelas do Orçamento',
                'db_table': 'orcamento_parcelas',
                'ordering': ['numero_parcela'],
            },
        ),
    ]
