# Generated by Django 6.0 on 2025-12-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_orcamento_numero_parcelas_orcamento_valor_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoparcela',
            name='descricao',
            field=models.CharField(blank=True, help_text='Ex: Entrada, 1/2, 2/2', max_length=200, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='orcamentoparcela',
            name='forma_pagamento',
            field=models.CharField(choices=[('A_VISTA', 'À Vista'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência Bancária'), ('CHEQUE', 'Cheque'), ('DINHEIRO', 'Dinheiro')], default='A_VISTA', max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
