# Generated by Django 6.0 on 2026-01-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_auto_desconto_global_auditoria'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orcamentohistorico',
            new_name='orcamento_h_timesta_94ffc8_idx',
            old_name='orcamento_h_timesta_idx',
        ),
    ]
