# Generated by Django 6.0 on 2026-01-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_rename_orcamento_h_timesta_idx_orcamento_h_timesta_94ffc8_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='num_visitas',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='visitas_cobradas',
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_previsao_termino',
            field=models.DateField(blank=True, help_text='Previsão de término do projeto', null=True, verbose_name='Previsão de Término'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='num_visitas_cobradas',
            field=models.IntegerField(default=0, help_text='Quantidade de visitas cobradas', verbose_name='Visitas Técnicas Cobradas'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='num_visitas_tecnicas',
            field=models.IntegerField(default=0, help_text='Total de visitas técnicas realizadas', verbose_name='Número de Visitas Técnicas'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='valor_total_visitas',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total das visitas técnicas cobradas', max_digits=12, verbose_name='Valor Total Visitas Cobradas'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_termino_real',
            field=models.DateField(blank=True, help_text='Data real de conclusão', null=True, verbose_name='Término do Projeto'),
        ),
    ]
