# Generated by Django 6.0 on 2026-01-03 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_rename_pessoa_emp_ativo_idx_cadastros_p_empresa_b3572f_idx_and_more'),
        ('projetos', '0011_remove_projeto_num_visitas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitatecnica',
            options={'ordering': ['-data_visita', '-hora_inicio'], 'verbose_name': 'Visita Técnica', 'verbose_name_plural': 'Visitas Técnicas'},
        ),
        migrations.RemoveField(
            model_name='visitatecnica',
            name='cobrada',
        ),
        migrations.RemoveField(
            model_name='visitatecnica',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='visitatecnica',
            name='projeto',
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='agendado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_agendadas', to=settings.AUTH_USER_MODEL, verbose_name='Agendado por'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='custo_visita',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Custo interno da visita', max_digits=10, verbose_name='Custo da Visita'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Agendamento'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário Fim'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário Início'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitas_tecnicas', to='projetos.orcamento', verbose_name='Orçamento'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='visitatecnica',
            name='data_visita',
            field=models.DateField(verbose_name='Data da Visita'),
        ),
        migrations.AlterField(
            model_name='visitatecnica',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição/Objetivo'),
        ),
        migrations.AlterField(
            model_name='visitatecnica',
            name='tecnico',
            field=models.ForeignKey(limit_choices_to={'vendedor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_tecnico', to='cadastros.pessoa', verbose_name='Técnico Responsável'),
        ),
        migrations.AlterField(
            model_name='visitatecnica',
            name='valor_cobrado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor cobrado do cliente', max_digits=10, verbose_name='Valor Cobrado'),
        ),
    ]
