# Generated by Django 6.0 on 2026-01-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0012_alter_visitatecnica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoitem',
            name='item_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Item'),
        ),
        migrations.AddField(
            model_name='orcamentoitem',
            name='item_ref',
            field=models.CharField(blank=True, help_text='Formato: tipo_id (ex: produto_1)', max_length=50, null=True, verbose_name='Referência do Item'),
        ),
    ]
