# Generated by Django 6.0 on 2026-01-12 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_rename_pessoa_emp_ativo_idx_cadastros_p_empresa_b3572f_idx_and_more'),
        ('projetos', '0013_orcamentoitem_item_codigo_orcamentoitem_item_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'cliente': True}, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_projeto', to='cadastros.pessoa', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_projeto_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='orcamentohistorico',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_projeto_historico', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
