# Generated by Django 6.0 on 2026-01-13 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0014_alter_orcamento_cliente_alter_orcamento_criado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do registro no diário', verbose_name='Data')),
                ('periodo', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('INTEGRAL', 'Dia Integral'), ('NOITE', 'Noite')], default='INTEGRAL', max_length=20, verbose_name='Período')),
                ('clima', models.CharField(choices=[('ENSOLARADO', 'Ensolarado'), ('NUBLADO', 'Nublado'), ('CHUVOSO', 'Chuvoso'), ('TEMPESTADE', 'Tempestade')], default='ENSOLARADO', max_length=20, verbose_name='Clima')),
                ('temperatura', models.CharField(blank=True, help_text='Ex: 25°C', max_length=50, null=True, verbose_name='Temperatura')),
                ('num_trabalhadores', models.IntegerField(default=0, help_text='Quantidade de trabalhadores presentes', verbose_name='Número de Trabalhadores')),
                ('equipe_descricao', models.TextField(blank=True, help_text='Funções e nomes dos trabalhadores', null=True, verbose_name='Descrição da Equipe')),
                ('equipamentos_utilizados', models.TextField(blank=True, help_text='Liste os equipamentos usados no dia', null=True, verbose_name='Equipamentos Utilizados')),
                ('atividades_realizadas', models.TextField(help_text='Descrição detalhada das atividades executadas', verbose_name='Atividades Realizadas')),
                ('percentual_progresso', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de conclusão das atividades planejadas para o dia', max_digits=5, verbose_name='Progresso do Dia (%)')),
                ('materiais_recebidos', models.TextField(blank=True, help_text='Materiais que chegaram na obra', null=True, verbose_name='Materiais Recebidos')),
                ('materiais_utilizados', models.TextField(blank=True, help_text='Materiais consumidos durante o dia', null=True, verbose_name='Materiais Utilizados')),
                ('problemas_encontrados', models.TextField(blank=True, help_text='Descreva problemas ou imprevistos', null=True, verbose_name='Problemas Encontrados')),
                ('solucoes_aplicadas', models.TextField(blank=True, help_text='Como os problemas foram resolvidos', null=True, verbose_name='Soluções Aplicadas')),
                ('visitas_fiscalizacao', models.TextField(blank=True, help_text='Registre visitas de fiscais, engenheiros, clientes, etc.', null=True, verbose_name='Visitas e Fiscalização')),
                ('incidentes_seguranca', models.TextField(blank=True, help_text='Acidentes, quase-acidentes ou questões de segurança', null=True, verbose_name='Incidentes de Segurança')),
                ('epi_utilizado', models.BooleanField(default=True, help_text='Todos os trabalhadores usaram EPIs adequados?', verbose_name='EPIs Utilizados?')),
                ('observacoes', models.TextField(blank=True, help_text='Outras informações relevantes', null=True, verbose_name='Observações Gerais')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diario_obra', to='projetos.projeto', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Diário da Obra',
                'verbose_name_plural': 'Diários da Obra',
                'db_table': 'diario_obra',
                'ordering': ['-data', '-criado_em'],
                'unique_together': {('projeto', 'data', 'periodo')},
            },
        ),
    ]
