# Generated by Django 6.0 on 2026-02-24 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_diarioobra'),
        ('usuarios', '0005_backupconfig_backupbancodados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaoprojeto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_projeto', to='usuarios.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='contacorrenteprojeto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contas_correntes_projeto', to='usuarios.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='diarioobra',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='diarios_obra', to='usuarios.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='usuarios.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='vendadireta',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_diretas', to='usuarios.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='vendadiretaitem',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_diretas_itens', to='usuarios.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_tecnicas', to='usuarios.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='codigo',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Código do Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor/Responsável'),
        ),
    ]
