# Generated by Django 6.0 on 2026-02-24 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0016_alocacaoprojeto_empresa_contacorrenteprojeto_empresa_and_more'),
        ('usuarios', '0005_backupconfig_backupbancodados'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_aprovacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='descricao',
            field=models.CharField(default='Orçamento', help_text='Descrição resumida do orçamento', max_length=200, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='usuarios.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONVERTIDO', 'Convertido em Projeto')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
    ]
