"""
Django settings for serrana project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-serrana-2025-empresarial-sistema-gestao-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Em desenvolvimento aceita localhost, em produção adicione seu domínio
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']  # Altere '*' para seu domínio em produção


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'cadastros',
    'estoque',
    'projetos',
    'vendas',
    'financeiro.apps.FinanceiroConfig',  # Carrega signals automaticamente
    'dashboard',  # Dashboard BI
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuarios.middleware_empresa.EmpresaAtivaMiddleware',  # Middleware de multiempresa
]

ROOT_URLCONF = 'serrana.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Custom context processors
                'serrana.context_processors.current_module',
                'serrana.context_processors.user_permissions',
                'usuarios.middleware_empresa.empresa_context_processor',  # Empresa ativa
            ],
        },
    },
]

WSGI_APPLICATION = 'serrana.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'serrana_empresarial',
        'USER': 'root',
        'PASSWORD': 'MBRHELP2023DEV@',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (Upload de arquivos)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Autenticação
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = 'usuarios:home_modulos'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Chave primária padrão
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sessão: encerra após 30 minutos sem atividade
SESSION_COOKIE_AGE = 30 * 60  # 30 minutos
SESSION_SAVE_EVERY_REQUEST = True

# ============================================
# REDIS CACHE CONFIGURAÇÃO
# ============================================

# NOTA: Para produção com Redis, instalar:
# https://github.com/microsoftarchive/redis/releases
# Ou: choco install redis-64

# Configuração com Redis (descomentar quando Redis estiver instalado)
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'KEY_PREFIX': 'serrana',
#         'TIMEOUT': 3600,  # 1 hora por padrão
#     }
# }

# Configuração com cache em memória (desenvolvimento sem Redis)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'serrana-cache',
        'TIMEOUT': 3600,  # 1 hora
    }
}

# ============================================
# CONFIGURAÇÕES DE E-MAIL
# ============================================

# Para desenvolvimento (console backend)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Para produção (descomentar e configurar):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # ou seu servidor SMTP
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'seu-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'sua-senha-de-app'
# DEFAULT_FROM_EMAIL = 'Sistema Serrana <seu-email@gmail.com>'

# Desenvolvimento
DEFAULT_FROM_EMAIL = 'sistema@serrana.com.br'

# ============================================
# CELERY CONFIGURAÇÕES
# ============================================

# Broker (Redis)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Configurações adicionais
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Sao_Paulo'
CELERY_ENABLE_UTC = True

# Configurações de retry
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# ============================================
# CELERY BEAT (Agendamento)
# ============================================

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Dashboard BI - Atualização de KPIs
    'atualizar-kpis-dashboard': {
        'task': 'dashboard.tasks.atualizar_kpis_dashboard',
        'schedule': crontab(minute=0),  # A cada hora cheia
    },
    'calcular-previsao-estoque': {
        'task': 'dashboard.tasks.calcular_previsao_estoque',
        'schedule': crontab(hour=6, minute=0),  # Todo dia às 06:00
    },
    'enviar-relatorio-gerencial': {
        'task': 'dashboard.tasks.enviar_relatorio_gerencial',
        'schedule': crontab(hour=8, minute=0, day_of_week=1),  # Segunda às 08:00
    },
    
    # Financeiro - Régua de Cobrança
    'processar-reguas-diarias': {
        'task': 'financeiro.tasks.processar_reguas_diarias',
        'schedule': crontab(hour=8, minute=0),  # Todo dia às 08:00
    },
    'reprocessar-falhas': {
        'task': 'financeiro.tasks.reprocessar_falhas_task',
        'schedule': crontab(hour='*/2'),  # A cada 2 horas
    },
    'limpar-logs-antigos': {
        'task': 'financeiro.tasks.limpar_logs_antigos',
        'schedule': crontab(hour=3, minute=0, day_of_week=1),  # Toda segunda às 03:00
    },
    # Budget - Verificação de budgets críticos
    'verificar-budgets-criticos-diario': {
        'task': 'financeiro.tasks.verificar_budgets_criticos_diario',
        'schedule': crontab(hour=8, minute=30),  # Todo dia às 08:30
    },
    'verificar-budgets-atrasados-diario': {
        'task': 'financeiro.tasks.verificar_budgets_atrasados_diario',
        'schedule': crontab(hour=9, minute=0),  # Todo dia às 09:00
    },
}

# ============================================
# CONFIGURAÇÕES DE BUDGET
# ============================================

# Emails dos gestores que recebem notificações de Budget
GESTORES_EMAILS = [
    'gestor@serrana.com.br',
    # Adicione outros emails de gestores aqui
]

# Limites de semáforo do Budget (percentuais)
BUDGET_SEMAFORO_AMARELO = 80  # Zona amarela a partir de 80%
BUDGET_SEMAFORO_VERMELHO = 95  # Zona vermelha a partir de 95%
BUDGET_BLOQUEIO_AUTOMATICO = True  # Bloqueia automaticamente ao atingir zona vermelha
