# Generated by Django 6.0 on 2026-01-12 20:43

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0007_rename_pessoa_emp_ativo_idx_cadastros_p_empresa_b3572f_idx_and_more'),
        ('projetos', '0014_alter_orcamento_cliente_alter_orcamento_criado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único da condição (ex: AV, 3X, ENT3X)', max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('A_VISTA', 'À Vista'), ('PARCELADO', 'Parcelado'), ('ENTRADA_PARCELAS', 'Entrada + Parcelas'), ('MEDICAO', 'Medição de Obra'), ('PERSONALIZADO', 'Personalizado')], max_length=20)),
                ('percentual_entrada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de entrada (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('numero_parcelas', models.PositiveIntegerField(default=1, help_text='Número total de parcelas (incluindo entrada)', validators=[django.core.validators.MinValueValidator(1)])),
                ('intervalo_dias', models.PositiveIntegerField(default=30, help_text='Intervalo em dias entre parcelas', validators=[django.core.validators.MinValueValidator(1)])),
                ('primeira_parcela_dias', models.PositiveIntegerField(default=0, help_text='Dias até a primeira parcela (0=à vista)')),
                ('medicoes_percentuais', models.JSONField(blank=True, help_text='Lista de percentuais para medições: [30, 40, 30]', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('padrao', models.BooleanField(default=False, help_text='Condição padrão ao criar orçamento')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condição de Pagamento',
                'verbose_name_plural': 'Condições de Pagamento',
                'db_table': 'vendas_condicao_pagamento',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, help_text='Gerado automaticamente: ORC-2025-0001', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado ao Cliente'), ('NEGOCIACAO', 'Em Negociação'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CANCELADO', 'Cancelado')], db_index=True, default='RASCUNHO', max_length=20)),
                ('data_orcamento', models.DateField(default=datetime.date.today, help_text='Data de criação do orçamento')),
                ('validade_ate', models.DateField(help_text='Até quando este orçamento é válido')),
                ('prazo_execucao_dias', models.PositiveIntegerField(default=30, help_text='Prazo previsto de execução em dias corridos')),
                ('endereco_execucao_logradouro', models.CharField(max_length=200)),
                ('endereco_execucao_numero', models.CharField(max_length=20)),
                ('endereco_execucao_complemento', models.CharField(blank=True, max_length=100)),
                ('endereco_execucao_bairro', models.CharField(max_length=100)),
                ('endereco_execucao_cidade', models.CharField(max_length=100)),
                ('endereco_execucao_estado', models.CharField(max_length=2)),
                ('endereco_execucao_cep', models.CharField(max_length=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Soma dos itens (sem desconto)', max_digits=15)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto global no orçamento', max_digits=15)),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outras_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Impostos, taxas, etc', max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor final do orçamento', max_digits=15)),
                ('custo_total_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Soma dos custos estimados (não aparece na proposta)', max_digits=15)),
                ('observacoes', models.TextField(blank=True, help_text='Observações que aparecem na proposta')),
                ('observacoes_internas', models.TextField(blank=True, help_text='Anotações internas (não aparecem na proposta)')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_reprovacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(limit_choices_to={'cliente': True}, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='cadastros.pessoa')),
                ('condicao_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='vendas.condicaopagamento')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('projeto_gerado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_vendas_origem', to='projetos.projeto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_vendidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'db_table': 'vendas_orcamento',
                'ordering': ['-data_orcamento', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROPOSTA', 'Proposta Comercial'), ('PLANTA', 'Planta/Projeto'), ('FOTO', 'Foto'), ('DOCUMENTO', 'Documento'), ('OUTRO', 'Outro')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='orcamentos/anexos/%Y/%m/')),
                ('versao', models.PositiveIntegerField(default=1)),
                ('data_envio', models.DateTimeField(blank=True, help_text='Data de envio ao cliente', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_criados', to=settings.AUTH_USER_MODEL)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_enviados', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='vendas.orcamento')),
            ],
            options={
                'verbose_name': 'Anexo de Orçamento',
                'verbose_name_plural': 'Anexos de Orçamentos',
                'db_table': 'vendas_orcamento_anexo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True, help_text='Descrição da alteração')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='vendas.orcamento')),
            ],
            options={
                'verbose_name': 'Histórico de Orçamento',
                'verbose_name_plural': 'Históricos de Orçamentos',
                'db_table': 'vendas_orcamento_historico',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na proposta')),
                ('descricao', models.CharField(help_text='Descrição que aparece na proposta', max_length=500)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unidade', models.CharField(default='UN', help_text='UN, M2, ML, KG, CJ, etc', max_length=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço de venda unitário', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('custo_unitario_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo estimado unitário (não aparece na proposta)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('desconto_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('largura', models.DecimalField(blank=True, decimal_places=2, help_text='Largura em metros', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Altura em metros', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('m2_calculado', models.DecimalField(blank=True, decimal_places=2, help_text='Área calculada (largura x altura)', max_digits=10, null=True)),
                ('cor', models.CharField(blank=True, max_length=100)),
                ('linha', models.CharField(blank=True, help_text='Linha do produto (ex: Suprema, Elegance)', max_length=100)),
                ('vidro', models.CharField(blank=True, help_text='Tipo de vidro (ex: Incolor 4mm, Fumê 6mm)', max_length=100)),
                ('acabamento', models.CharField(blank=True, help_text='Acabamento (ex: Anodizado, Eletrostático)', max_length=100)),
                ('observacao_tecnica', models.TextField(blank=True, help_text='Detalhes técnicos (aparecem na proposta)')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.orcamento')),
                ('produto', models.ForeignKey(blank=True, help_text='Produto do cadastro (ou deixe vazio para texto livre)', null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
                'db_table': 'vendas_orcamento_item',
                'ordering': ['orcamento', 'ordem'],
            },
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['status', 'data_orcamento'], name='vendas_orca_status_6269eb_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['cliente', 'status'], name='vendas_orca_cliente_034268_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['vendedor', 'data_orcamento'], name='vendas_orca_vendedo_ccbfb3_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['data_orcamento'], name='vendas_orca_data_or_51ca18_idx'),
        ),
    ]
