# Generated by Django 6.0 on 2026-01-01 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Municipal')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo')),
                ('cor_primaria', models.CharField(default='#0066cc', help_text='Código hexadecimal (#RRGGBB)', max_length=7, verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(default='#333333', help_text='Código hexadecimal (#RRGGBB)', max_length=7, verbose_name='Cor Secundária')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URLs amigáveis', max_length=100, unique=True, verbose_name='Slug')),
                ('ativa', models.BooleanField(default=True, help_text='Empresas inativas não podem ser acessadas', verbose_name='Ativa')),
                ('empresa_matriz', models.BooleanField(default=False, help_text='Define se é a empresa matriz do grupo', verbose_name='É Matriz')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsavel', models.ForeignKey(blank=True, help_text='Usuário responsável pela empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['-empresa_matriz', 'razao_social'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(blank=True, help_text='Ex: Administrador, Operador, Financeiro', max_length=50, verbose_name='Papel')),
                ('ativo', models.BooleanField(default=True, help_text='Define se o usuário tem acesso ativo a esta empresa', verbose_name='Acesso Ativo')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Data em que o acesso expira', null=True, verbose_name='Data de Término')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_empresa_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_usuarios', to='usuarios.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_empresas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário x Empresa',
                'verbose_name_plural': 'Usuários x Empresas',
                'db_table': 'usuarios_empresas',
                'ordering': ['usuario__username', 'empresa__nome_fantasia'],
            },
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cnpj'], name='empresas_cnpj_009d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['slug'], name='empresas_slug_1a17f5_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['ativa'], name='empresas_ativa_ae071f_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarioempresa',
            index=models.Index(fields=['usuario', 'empresa'], name='usuarios_em_usuario_a85dca_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarioempresa',
            index=models.Index(fields=['ativo'], name='usuarios_em_ativo_68d972_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioempresa',
            unique_together={('usuario', 'empresa')},
        ),
    ]
