# Generated by Django 6.0 on 2026-01-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empresa_usuarioempresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='smtp_ativo',
            field=models.BooleanField(default=False, help_text='Usar SMTP próprio ao invés do padrão do sistema', verbose_name='SMTP Ativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_from_email',
            field=models.EmailField(blank=True, help_text='E-mail que aparecerá como remetente', max_length=254, verbose_name='E-mail Remetente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_from_name',
            field=models.CharField(blank=True, help_text='Nome que aparecerá como remetente', max_length=100, verbose_name='Nome Remetente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='Ex: smtp.gmail.com', max_length=200, verbose_name='Servidor SMTP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Senha ou senha de aplicativo', max_length=200, verbose_name='Senha SMTP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_port',
            field=models.IntegerField(blank=True, default=587, help_text='Porta padrão: 587 (TLS) ou 465 (SSL)', null=True, verbose_name='Porta SMTP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Usar conexão SSL (porta 465)', verbose_name='Usar SSL'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Usar conexão TLS (recomendado)', verbose_name='Usar TLS'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_username',
            field=models.CharField(blank=True, help_text='Geralmente é o e-mail', max_length=200, verbose_name='Usuário SMTP'),
        ),
    ]
