# Generated by Django 6.0 on 2026-01-12 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_regimetributario_projectbudget_justificativabudget_and_more'),
        ('usuarios', '0003_empresa_smtp_ativo_empresa_smtp_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='regime_tributario',
            field=models.ForeignKey(blank=True, help_text='Regime tributário da empresa (Simples, Lucro Presumido, etc)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='financeiro.regimetributario', verbose_name='Regime Tributário'),
        ),
    ]
