# Generated by Django 6.0.1 on 2026-01-19 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_empresa_regime_tributario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False, help_text='Ativa ou desativa os backups agendados', verbose_name='Backup Agendado Habilitado')),
                ('frequencia', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='diaria', help_text='Frequência de execução dos backups', max_length=10, verbose_name='Frequência')),
                ('hora_execucao', models.TimeField(default='03:00', help_text='Hora em que o backup deve ser executado', verbose_name='Hora de Execução')),
                ('dia_semana', models.CharField(choices=[('0', 'Segunda-feira'), ('1', 'Terça-feira'), ('2', 'Quarta-feira'), ('3', 'Quinta-feira'), ('4', 'Sexta-feira'), ('5', 'Sábado'), ('6', 'Domingo')], default='0', help_text='Dia da semana para backups semanais (0=Segunda, 6=Domingo)', max_length=1, verbose_name='Dia da Semana')),
                ('dia_mes', models.IntegerField(default=1, help_text='Dia do mês para backups mensais (1-28)', verbose_name='Dia do Mês')),
                ('manter_ultimos_n', models.IntegerField(default=10, help_text='Quantidade de backups recentes a manter (0 = ilimitado)', verbose_name='Manter Últimos N Backups')),
                ('manter_dias', models.IntegerField(default=30, help_text='Dias para manter backups antigos (0 = ilimitado)', verbose_name='Manter Backups por Dias')),
                ('ultima_execucao', models.DateTimeField(blank=True, help_text='Data/hora da última execução do backup agendado', null=True, verbose_name='Última Execução')),
                ('status_ultima_execucao', models.CharField(blank=True, choices=[('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], max_length=20, null=True, verbose_name='Status Última Execução')),
                ('mensagem_ultima_execucao', models.TextField(blank=True, default='', help_text='Detalhes ou erros da última execução', verbose_name='Mensagem Última Execução')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backupconfig_atualizacoes', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração de Backup',
                'verbose_name_plural': 'Configurações de Backup',
                'db_table': 'usuarios_backupconfig',
            },
        ),
        migrations.CreateModel(
            name='BackupBancoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('caminho_arquivo', models.CharField(help_text='Caminho completo do arquivo de backup', max_length=500, verbose_name='Caminho do Arquivo')),
                ('tamanho_bytes', models.BigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='processando', max_length=20, verbose_name='Status')),
                ('database_name', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('tempo_execucao_segundos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tempo de Execução (s)')),
                ('mensagem_erro', models.TextField(blank=True, help_text='Detalhes do erro caso o backup falhe', verbose_name='Mensagem de Erro')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('data_expiracao', models.DateTimeField(blank=True, help_text='Data após a qual o backup pode ser excluído', null=True, verbose_name='Data de Expiração')),
                ('tipo_backup', models.CharField(choices=[('manual', 'Manual'), ('agendado', 'Agendado')], default='manual', help_text='Manual (gerado por usuário) ou Agendado (automático)', max_length=10, verbose_name='Tipo de Backup')),
                ('protegido', models.BooleanField(default=False, help_text='Backups protegidos não são excluídos pela política de retenção', verbose_name='Protegido')),
                ('empresa', models.ForeignKey(help_text='Empresa para qual o backup foi gerado', on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='usuarios.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Backup de Banco de Dados',
                'verbose_name_plural': 'Backups de Banco de Dados',
                'db_table': 'backup_banco_dados',
                'ordering': ['-criado_em'],
                'permissions': [('gerar_backup', 'Pode gerar backup do banco de dados'), ('download_backup', 'Pode fazer download de backups')],
                'indexes': [models.Index(fields=['-criado_em'], name='backup_banc_criado__59418b_idx'), models.Index(fields=['empresa', 'status'], name='backup_banc_empresa_131df7_idx'), models.Index(fields=['status'], name='backup_banc_status_fb9702_idx')],
            },
        ),
    ]
