# Generated by Django 6.0 on 2026-03-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_backupconfig_backupbancodados'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='vendedor',
            field=models.BooleanField(default=False, help_text='Marca este usuário como vendedor e cria/vincula automaticamente o cadastro de Pessoa', verbose_name='É Vendedor'),
        ),
    ]
