# Generated by Django 6.0 on 2025-12-30 13:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_remove_pessoa_celular_remove_pessoa_rg_ie_and_more'),
        ('projetos', '0002_alter_alocacaoprojeto_movimentacao_estoque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCustoVariabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('tipo', models.CharField(choices=[('FIXO', 'Custo Fixo'), ('VARIAVEL', 'Custo Variável'), ('MISTO', 'Custo Misto')], default='MISTO', max_length=10, verbose_name='Tipo de Custo')),
                ('percentual_variavel', models.DecimalField(decimal_places=2, default=0, help_text='Para custos mistos: % que é variável', max_digits=5, verbose_name='% Variável')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Classificação de Variabilidade',
                'verbose_name_plural': 'Classificações de Variabilidade',
                'db_table': 'categorias_custo_variabilidade',
            },
        ),
        migrations.CreateModel(
            name='ParcelaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField(verbose_name='Nº Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Original')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Pago')),
                ('saldo_aberto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo em Aberto')),
                ('status', models.CharField(choices=[('ABERTO', 'Em Aberto'), ('PARCIAL', 'Parcialmente Quitado'), ('QUITADO', 'Quitado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Parcela Financeira',
                'verbose_name_plural': 'Parcelas Financeiras',
                'db_table': 'parcelas_financeiras',
                'ordering': ['titulo', 'numero_parcela'],
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_compe', models.CharField(help_text='Código de 3 dígitos do Banco Central', max_length=3, unique=True, verbose_name='Código COMPE')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bancos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'bancos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('OBRA', 'Obra/Projeto'), ('ADMINISTRATIVO', 'Administrativo'), ('PRODUCAO', 'Produção'), ('COMERCIAL', 'Comercial'), ('LOJA', 'Loja/Showroom'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_custo_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.projeto', verbose_name='Projeto Relacionado')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_custo_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'db_table': 'centros_custo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Caixa Matriz, Bradesco CC 1234-5', max_length=100, verbose_name='Nome da Conta')),
                ('tipo', models.CharField(choices=[('CONTA_CORRENTE', 'Conta Corrente'), ('CONTA_POUPANCA', 'Conta Poupança'), ('CONTA_INVESTIMENTO', 'Conta Investimento'), ('CAIXA', 'Caixa'), ('CARTEIRA_DIGITAL', 'Carteira Digital (PicPay, PayPal, etc)')], max_length=20, verbose_name='Tipo')),
                ('agencia', models.CharField(blank=True, max_length=10, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=20, verbose_name='Conta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Saldo na data de implantação', max_digits=15, verbose_name='Saldo Inicial')),
                ('data_saldo_inicial', models.DateField(default=datetime.date.today, verbose_name='Data do Saldo Inicial')),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Limite de Crédito')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('banco', models.ForeignKey(blank=True, help_text='Obrigatório para contas bancárias', null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco', verbose_name='Banco')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Conta Financeira',
                'verbose_name_plural': 'Contas Financeiras',
                'db_table': 'contas_financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência Bancária'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CHEQUE', 'Cheque'), ('DEPOSITO', 'Depósito'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('prazo_compensacao', models.IntegerField(default=0, help_text='Dias até o dinheiro entrar efetivamente', verbose_name='Prazo de Compensação (dias)')),
                ('taxa_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Taxa percentual sobre o valor', max_digits=5, verbose_name='Taxa %')),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa Fixa R$')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formas_pagamento_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'db_table': 'formas_pagamento',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='BaixaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=datetime.date.today, verbose_name='Data de Pagamento')),
                ('valor_principal', models.DecimalField(decimal_places=2, help_text='Valor da parcela sendo baixado', max_digits=15, verbose_name='Valor Principal')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Multa')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Desconto')),
                ('taxas', models.DecimalField(decimal_places=2, default=0, help_text='Taxas da forma de pagamento', max_digits=15, verbose_name='Taxas')),
                ('valor_liquido', models.DecimalField(decimal_places=2, help_text='Valor efetivamente movimentado', max_digits=15, verbose_name='Valor Líquido')),
                ('estornado', models.BooleanField(default=False, verbose_name='Estornado')),
                ('data_estorno', models.DateTimeField(blank=True, null=True, verbose_name='Data do Estorno')),
                ('motivo_estorno', models.TextField(blank=True, verbose_name='Motivo do Estorno')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('estornado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_estornadas', to=settings.AUTH_USER_MODEL, verbose_name='Estornado por')),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.contafinanceira', verbose_name='Conta Financeira')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.formapagamento', verbose_name='Forma de Pagamento')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.parcelafinanceira', verbose_name='Parcela')),
            ],
            options={
                'verbose_name': 'Baixa Financeira',
                'verbose_name_plural': 'Baixas Financeiras',
                'db_table': 'baixas_financeiras',
                'ordering': ['-data_pagamento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('data_movimentacao', models.DateField(db_index=True, verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('estornado', models.BooleanField(default=False, verbose_name='Estornado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('baixa_financeira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.baixafinanceira', verbose_name='Baixa Relacionada')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto', verbose_name='Centro de Custo')),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.contafinanceira', verbose_name='Conta Financeira')),
            ],
            options={
                'verbose_name': 'Movimentação de Conta',
                'verbose_name_plural': 'Movimentações de Contas',
                'db_table': 'movimentacoes_contas',
                'ordering': ['-data_movimentacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TituloFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGAR', 'Conta a Pagar'), ('RECEBER', 'Conta a Receber')], max_length=10, verbose_name='Tipo')),
                ('numero_documento', models.CharField(help_text='NF, Contrato, Ordem, etc', max_length=50, verbose_name='Nº Documento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data_emissao', models.DateField(default=datetime.date.today, verbose_name='Data de Emissão')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('num_parcelas', models.IntegerField(default=1, verbose_name='Número de Parcelas')),
                ('intervalo_dias', models.IntegerField(default=30, verbose_name='Intervalo entre Parcelas (dias)')),
                ('status', models.CharField(choices=[('ABERTO', 'Em Aberto'), ('PARCIAL', 'Parcialmente Quitado'), ('QUITADO', 'Quitado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto', verbose_name='Centro de Custo')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pessoa', verbose_name='Cliente/Fornecedor')),
            ],
            options={
                'verbose_name': 'Título Financeiro',
                'verbose_name_plural': 'Títulos Financeiros',
                'db_table': 'titulos_financeiros',
                'ordering': ['-data_emissao', '-id'],
            },
        ),
        migrations.AddField(
            model_name='parcelafinanceira',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.titulofinanceiro', verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='TransferenciaEntreContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateField(default=datetime.date.today, verbose_name='Data da Transferência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('taxa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('estornado', models.BooleanField(default=False, verbose_name='Estornado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('conta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='financeiro.contafinanceira', verbose_name='Conta Destino')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_saida', to='financeiro.contafinanceira', verbose_name='Conta Origem')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('movimentacao_entrada', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencia_entrada_rel', to='financeiro.movimentacaoconta')),
                ('movimentacao_saida', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencia_saida_rel', to='financeiro.movimentacaoconta')),
            ],
            options={
                'verbose_name': 'Transferência entre Contas',
                'verbose_name_plural': 'Transferências entre Contas',
                'db_table': 'transferencias_entre_contas',
                'ordering': ['-data_transferencia', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='banco',
            index=models.Index(fields=['codigo_compe'], name='bancos_codigo__8f8012_idx'),
        ),
        migrations.AddIndex(
            model_name='centrocusto',
            index=models.Index(fields=['tipo'], name='centros_cus_tipo_d74add_idx'),
        ),
        migrations.AddIndex(
            model_name='centrocusto',
            index=models.Index(fields=['ativo'], name='centros_cus_ativo_91328b_idx'),
        ),
        migrations.AddIndex(
            model_name='contafinanceira',
            index=models.Index(fields=['tipo'], name='contas_fina_tipo_780fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='contafinanceira',
            index=models.Index(fields=['ativo'], name='contas_fina_ativo_c5e450_idx'),
        ),
        migrations.AddIndex(
            model_name='formapagamento',
            index=models.Index(fields=['tipo'], name='formas_paga_tipo_ab5022_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoconta',
            index=models.Index(fields=['conta_financeira', 'data_movimentacao'], name='movimentaco_conta_f_1fe30e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoconta',
            index=models.Index(fields=['tipo'], name='movimentaco_tipo_8e9b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoconta',
            index=models.Index(fields=['estornado'], name='movimentaco_estorna_83e09a_idx'),
        ),
        migrations.AddIndex(
            model_name='baixafinanceira',
            index=models.Index(fields=['parcela'], name='baixas_fina_parcela_385061_idx'),
        ),
        migrations.AddIndex(
            model_name='baixafinanceira',
            index=models.Index(fields=['data_pagamento'], name='baixas_fina_data_pa_921c98_idx'),
        ),
        migrations.AddIndex(
            model_name='baixafinanceira',
            index=models.Index(fields=['conta_financeira'], name='baixas_fina_conta_f_45916f_idx'),
        ),
        migrations.AddIndex(
            model_name='baixafinanceira',
            index=models.Index(fields=['estornado'], name='baixas_fina_estorna_30d0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='titulofinanceiro',
            index=models.Index(fields=['tipo', 'status'], name='titulos_fin_tipo_62907f_idx'),
        ),
        migrations.AddIndex(
            model_name='titulofinanceiro',
            index=models.Index(fields=['pessoa'], name='titulos_fin_pessoa__1cea1d_idx'),
        ),
        migrations.AddIndex(
            model_name='titulofinanceiro',
            index=models.Index(fields=['data_emissao'], name='titulos_fin_data_em_2a3624_idx'),
        ),
        migrations.AddIndex(
            model_name='titulofinanceiro',
            index=models.Index(fields=['centro_custo'], name='titulos_fin_centro__f36146_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelafinanceira',
            index=models.Index(fields=['titulo', 'numero_parcela'], name='parcelas_fi_titulo__b0314a_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelafinanceira',
            index=models.Index(fields=['data_vencimento', 'status'], name='parcelas_fi_data_ve_7df958_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelafinanceira',
            index=models.Index(fields=['status'], name='parcelas_fi_status_5a93cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parcelafinanceira',
            unique_together={('titulo', 'numero_parcela')},
        ),
        migrations.AddIndex(
            model_name='transferenciaentrecontas',
            index=models.Index(fields=['data_transferencia'], name='transferenc_data_tr_a7ddc2_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciaentrecontas',
            index=models.Index(fields=['estornado'], name='transferenc_estorna_3d66b2_idx'),
        ),
    ]
