# Generated by Django 6.0 on 2025-12-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('projetos', '0002_alter_alocacaoprojeto_movimentacao_estoque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulofinanceiro',
            name='conta_financeira_padrao',
            field=models.ForeignKey(blank=True, help_text='Conta/banco de onde sairá o pagamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contafinanceira', verbose_name='Conta Financeira Padrão'),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='projeto',
            field=models.ForeignKey(blank=True, help_text='Vínculo direto com projeto/obra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.projeto', verbose_name='Projeto'),
        ),
    ]
