# Generated by Django 6.0 on 2025-12-30 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_titulofinanceiro_conta_financeira_padrao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: 1.1.01, 3.2.01.001', max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('PATRIMONIO', 'Patrimônio Líquido')], max_length=15, verbose_name='Tipo')),
                ('natureza', models.CharField(choices=[('ANALITICA', 'Analítica'), ('SINTETICA', 'Sintética')], default='ANALITICA', max_length=10, verbose_name='Natureza')),
                ('nivel', models.IntegerField(default=1, editable=False, help_text='Nível na hierarquia', verbose_name='Nível')),
                ('caminho', models.CharField(editable=False, help_text='Caminho completo na hierarquia', max_length=255, verbose_name='Caminho')),
                ('aceita_lancamento', models.BooleanField(default=True, help_text='Contas sintéticas não aceitam lançamento direto', verbose_name='Aceita Lançamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('conta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_filhas', to='financeiro.planoconta', verbose_name='Conta Pai')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_conta_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Plano de Conta',
                'verbose_name_plural': 'Plano de Contas',
                'db_table': 'plano_contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='plano_conta',
            field=models.ForeignKey(blank=True, help_text='Classificação contábil da receita/despesa', limit_choices_to={'aceita_lancamento': True, 'ativo': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.planoconta', verbose_name='Plano de Contas'),
        ),
        migrations.AddIndex(
            model_name='planoconta',
            index=models.Index(fields=['tipo'], name='plano_conta_tipo_632283_idx'),
        ),
        migrations.AddIndex(
            model_name='planoconta',
            index=models.Index(fields=['natureza'], name='plano_conta_naturez_11388c_idx'),
        ),
        migrations.AddIndex(
            model_name='planoconta',
            index=models.Index(fields=['ativo'], name='plano_conta_ativo_1f28eb_idx'),
        ),
        migrations.AddIndex(
            model_name='planoconta',
            index=models.Index(fields=['caminho'], name='plano_conta_caminho_4c6a01_idx'),
        ),
    ]
