# Generated by Django 6.0 on 2025-12-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_pessoa_celular_remove_pessoa_rg_ie_and_more'),
        ('financeiro', '0003_planoconta_titulofinanceiro_plano_conta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulofinanceiro',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.pessoa', verbose_name='Cliente/Fornecedor'),
        ),
    ]
