# Generated by Django 6.0 on 2025-12-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_tornar_pessoa_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulofinanceiro',
            name='data_primeiro_vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento da primeira parcela', null=True, verbose_name='Data do 1º Vencimento'),
        ),
    ]
