# Generated by Django 6.0 on 2025-12-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_adicionar_data_primeiro_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulofinanceiro',
            name='intervalos_personalizados',
            field=models.CharField(blank=True, help_text='Ex: 30/45/60 para vencimentos variáveis', max_length=200, null=True, verbose_name='Intervalos Personalizados'),
        ),
    ]
