# Generated by Django 5.0 on 2025-01-01 23:00

from django.db import migrations


def popular_empresa_padrao(apps, schema_editor):
    """Popula empresa padrão em todos os registros"""
    Empresa = apps.get_model('usuarios', 'Empresa')
    ContaFinanceira = apps.get_model('financeiro', 'ContaFinanceira')
    FormaPagamento = apps.get_model('financeiro', 'FormaPagamento')
    CentroCusto = apps.get_model('financeiro', 'CentroCusto')
    PlanoConta = apps.get_model('financeiro', 'PlanoConta')
    TituloFinanceiro = apps.get_model('financeiro', 'TituloFinanceiro')
    CategoriaCustoVariabilidade = apps.get_model('financeiro', 'CategoriaCustoVariabilidade')
    
    # Busca empresa padrão (primeira)
    empresa_padrao = Empresa.objects.first()
    
    if empresa_padrao:
        # Atualiza todos os registros
        ContaFinanceira.objects.filter(empresa__isnull=True).update(empresa=empresa_padrao)
        FormaPagamento.objects.filter(empresa__isnull=True).update(empresa=empresa_padrao)
        CentroCusto.objects.filter(empresa__isnull=True).update(empresa=empresa_padrao)
        PlanoConta.objects.filter(empresa__isnull=True).update(empresa=empresa_padrao)
        TituloFinanceiro.objects.filter(empresa__isnull=True).update(empresa=empresa_padrao)
        CategoriaCustoVariabilidade.objects.filter(empresa__isnull=True).update(empresa=empresa_padrao)


def reverter_popular_empresa(apps, schema_editor):
    """Reverte populando empresa"""
    ContaFinanceira = apps.get_model('financeiro', 'ContaFinanceira')
    FormaPagamento = apps.get_model('financeiro', 'FormaPagamento')
    CentroCusto = apps.get_model('financeiro', 'CentroCusto')
    PlanoConta = apps.get_model('financeiro', 'PlanoConta')
    TituloFinanceiro = apps.get_model('financeiro', 'TituloFinanceiro')
    CategoriaCustoVariabilidade = apps.get_model('financeiro', 'CategoriaCustoVariabilidade')
    
    ContaFinanceira.objects.all().update(empresa=None)
    FormaPagamento.objects.all().update(empresa=None)
    CentroCusto.objects.all().update(empresa=None)
    PlanoConta.objects.all().update(empresa=None)
    TituloFinanceiro.objects.all().update(empresa=None)
    CategoriaCustoVariabilidade.objects.all().update(empresa=None)


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_adicionar_empresa_nullable'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(popular_empresa_padrao, reverter_popular_empresa),
    ]
