# Generated by Django 5.0 on 2025-01-01 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_popular_empresa_padrao'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        # Torna empresa obrigatória
        migrations.AlterField(
            model_name='contafinanceira',
            name='empresa',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='contas_financeiras',
                to='usuarios.empresa',
                verbose_name='Empresa'
            ),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='empresa',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='formas_pagamento',
                to='usuarios.empresa',
                verbose_name='Empresa'
            ),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='empresa',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='centros_custo',
                to='usuarios.empresa',
                verbose_name='Empresa'
            ),
        ),
        migrations.AlterField(
            model_name='planoconta',
            name='empresa',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='planos_conta',
                to='usuarios.empresa',
                verbose_name='Empresa'
            ),
        ),
        migrations.AlterField(
            model_name='titulofinanceiro',
            name='empresa',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='titulos_financeiros',
                to='usuarios.empresa',
                verbose_name='Empresa'
            ),
        ),
        migrations.AlterField(
            model_name='categoriacustovariabilidade',
            name='empresa',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='categorias_custo',
                to='usuarios.empresa',
                verbose_name='Empresa'
            ),
        ),
        
        # Adiciona unique_together para evitar duplicação entre empresas
        migrations.AlterUniqueTogether(
            name='formapagamento',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='centrocusto',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='planoconta',
            unique_together={('empresa', 'codigo')},
        ),
    ]
