# Generated by Django 6.0 on 2026-01-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_empresa_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoconta',
            name='centro_custo',
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='planoconta',
            name='codigo',
            field=models.CharField(help_text='Ex: 1.1.01, 3.2.01.001', max_length=20, verbose_name='Código'),
        ),
    ]
