# Generated by Django 6.0 on 2026-01-03 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_remove_movimentacaoconta_centro_custo_and_more'),
        ('usuarios', '0002_empresa_usuarioempresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelafinanceira',
            name='contato_email_override',
            field=models.EmailField(blank=True, help_text='Deixe em branco para usar e-mail do cliente', max_length=255, null=True, verbose_name='E-mail para Cobrança'),
        ),
        migrations.AddField(
            model_name='parcelafinanceira',
            name='data_promessa_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Promessa de Pagamento'),
        ),
        migrations.AddField(
            model_name='parcelafinanceira',
            name='observacao_promessa',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da Promessa'),
        ),
        migrations.AddField(
            model_name='parcelafinanceira',
            name='pausar_regua_ate',
            field=models.DateField(blank=True, help_text='Pausar envios até esta data', null=True, verbose_name='Pausar Régua Até'),
        ),
        migrations.AddField(
            model_name='parcelafinanceira',
            name='regua_ativa',
            field=models.BooleanField(default=False, help_text='Ativar régua de cobrança automática', verbose_name='Régua Ativa'),
        ),
        migrations.AddField(
            model_name='parcelafinanceira',
            name='status_cobranca',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('NEGOCIACAO', 'Em Negociação'), ('PROMESSA', 'Promessa de Pagamento'), ('INTENSA', 'Cobrança Intensa'), ('BLOQUEADA', 'Bloqueada')], default='NORMAL', max_length=20, verbose_name='Status de Cobrança'),
        ),
        migrations.CreateModel(
            name='ReguaCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Régua Padrão, Régua Clientes VIP', max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reguas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reguas_cobranca', to='usuarios.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Régua de Cobrança',
                'verbose_name_plural': 'Réguas de Cobrança',
                'db_table': 'reguas_cobranca',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='parcelafinanceira',
            name='regua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas', to='financeiro.reguacobranca', verbose_name='Régua de Cobrança'),
        ),
        migrations.CreateModel(
            name='ReguaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(help_text='Ordem de execução', verbose_name='Ordem')),
                ('nome', models.CharField(help_text='Ex: Lembrete Amigável, Cobrança Firme', max_length=100, verbose_name='Nome')),
                ('offset_dias', models.IntegerField(help_text='Dias relativos ao vencimento. Negativo = antes, 0 = no dia, positivo = depois', verbose_name='Offset em Dias')),
                ('enviar_email', models.BooleanField(default=True, verbose_name='Enviar E-mail')),
                ('assunto_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Assunto do E-mail')),
                ('template_email', models.TextField(blank=True, help_text='Use variáveis: {cliente_nome}, {parcela_valor}, {parcela_vencimento}, {parcela_numero}, {empresa_nome}, {dias_atraso}', null=True, verbose_name='Template E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('regua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='financeiro.reguacobranca', verbose_name='Régua')),
            ],
            options={
                'verbose_name': 'Etapa da Régua',
                'verbose_name_plural': 'Etapas das Réguas',
                'db_table': 'reguas_etapas',
                'ordering': ['regua', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='LogCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('EMAIL', 'E-mail')], max_length=20, verbose_name='Canal')),
                ('status', models.CharField(choices=[('ENFILEIRADO', 'Enfileirado'), ('PROCESSANDO', 'Processando'), ('ENVIADO', 'Enviado com Sucesso'), ('FALHA', 'Falha no Envio'), ('CANCELADO', 'Cancelado')], default='ENFILEIRADO', max_length=20, verbose_name='Status')),
                ('destinatario', models.CharField(help_text='E-mail do destinatário', max_length=255, verbose_name='Destinatário')),
                ('assunto', models.CharField(blank=True, max_length=500, null=True, verbose_name='Assunto')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem Enviada')),
                ('tentativas', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('max_tentativas', models.PositiveIntegerField(default=3, verbose_name='Máximo de Tentativas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_tentativa', models.DateTimeField(blank=True, null=True, verbose_name='Última Tentativa')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('erro', models.TextField(blank=True, null=True, verbose_name='Erro')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Mensagem')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_cobranca', to='financeiro.parcelafinanceira', verbose_name='Parcela')),
                ('etapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='financeiro.reguaetapa', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Log de Cobrança',
                'verbose_name_plural': 'Logs de Cobrança',
                'db_table': 'logs_cobranca',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='reguacobranca',
            index=models.Index(fields=['empresa', 'ativa'], name='reguas_cobr_empresa_62b9d4_idx'),
        ),
        migrations.AddIndex(
            model_name='reguaetapa',
            index=models.Index(fields=['regua', 'ativo'], name='reguas_etap_regua_i_fc406f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reguaetapa',
            unique_together={('regua', 'ordem')},
        ),
        migrations.AddIndex(
            model_name='logcobranca',
            index=models.Index(fields=['parcela', 'status'], name='logs_cobran_parcela_db855a_idx'),
        ),
        migrations.AddIndex(
            model_name='logcobranca',
            index=models.Index(fields=['status', 'data_criacao'], name='logs_cobran_status_471a71_idx'),
        ),
        migrations.AddIndex(
            model_name='logcobranca',
            index=models.Index(fields=['etapa'], name='logs_cobran_etapa_i_c458d1_idx'),
        ),
    ]
