# Generated by Django 6.0 on 2026-01-12 20:43

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_rename_pessoa_emp_ativo_idx_cadastros_p_empresa_b3572f_idx_and_more'),
        ('financeiro', '0011_parcelafinanceira_contato_email_override_and_more'),
        ('projetos', '0013_orcamentoitem_item_codigo_orcamentoitem_item_ref'),
        ('usuarios', '0003_empresa_smtp_ativo_empresa_smtp_from_email_and_more'),
        ('vendas', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimeTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('SIMPLES_NACIONAL', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO_REAL', 'Lucro Real'), ('MEI', 'Microempreendedor Individual')], max_length=30, unique=True, verbose_name='Regime')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Regime Tributário',
                'verbose_name_plural': 'Regimes Tributários',
                'db_table': 'regimes_tributarios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado'), ('EM_EXECUCAO', 'Em Execução'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('custo_aluminio_previsto', models.DecimalField(decimal_places=2, default=0, help_text='Custo total previsto de perfis de alumínio', max_digits=15, verbose_name='Custo Alumínio Previsto')),
                ('custo_vidro_previsto', models.DecimalField(decimal_places=2, default=0, help_text='Custo total previsto de vidros', max_digits=15, verbose_name='Custo Vidro Previsto')),
                ('custo_acessorios_previsto', models.DecimalField(decimal_places=2, default=0, help_text='Custo total previsto de acessórios (fechaduras, dobradiças, etc)', max_digits=15, verbose_name='Custo Acessórios Previsto')),
                ('custo_outros_materiais_previsto', models.DecimalField(decimal_places=2, default=0, help_text='Outros materiais não classificados', max_digits=15, verbose_name='Custo Outros Materiais Previsto')),
                ('km_estimado', models.DecimalField(decimal_places=2, default=0, help_text='Quilometragem estimada para o projeto', max_digits=10, verbose_name='KM Estimado')),
                ('valor_combustivel_litro', models.DecimalField(decimal_places=2, default=0, help_text='Valor do litro do combustível', max_digits=6, verbose_name='Valor Combustível/Litro')),
                ('consumo_medio_km_litro', models.DecimalField(decimal_places=2, default=10, help_text='Consumo médio do veículo em km/litro', max_digits=5, verbose_name='Consumo Médio (km/L)')),
                ('custo_pedagios_previsto', models.DecimalField(decimal_places=2, default=0, help_text='Estimativa de gastos com pedágios', max_digits=10, verbose_name='Custo Pedágios Previsto')),
                ('custo_estacionamento_previsto', models.DecimalField(decimal_places=2, default=0, help_text='Estimativa de gastos com estacionamento', max_digits=10, verbose_name='Custo Estacionamento Previsto')),
                ('horas_fabricacao_previstas', models.DecimalField(decimal_places=2, default=0, help_text='Total de horas previstas para fabricação', max_digits=8, verbose_name='Horas Fabricação Previstas')),
                ('valor_hora_fabricacao', models.DecimalField(decimal_places=2, default=0, help_text='Custo por hora de fabricação', max_digits=10, verbose_name='Valor Hora Fabricação')),
                ('horas_montagem_previstas', models.DecimalField(decimal_places=2, default=0, help_text='Total de horas previstas para montagem/instalação', max_digits=8, verbose_name='Horas Montagem Previstas')),
                ('valor_hora_montagem', models.DecimalField(decimal_places=2, default=0, help_text='Custo por hora de montagem/instalação', max_digits=10, verbose_name='Valor Hora Montagem')),
                ('custos_administrativos_previsto', models.DecimalField(decimal_places=2, default=0, help_text='Rateio de custos administrativos', max_digits=15, verbose_name='Custos Administrativos Previsto')),
                ('custos_extras_previsto', models.DecimalField(decimal_places=2, default=0, help_text='Margem para imprevistos', max_digits=15, verbose_name='Custos Extras Previsto')),
                ('custo_total_previsto', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Soma de todos os custos previstos', max_digits=15, verbose_name='Custo Total Previsto')),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0, help_text='Valor total da venda (do orçamento aprovado)', max_digits=15, verbose_name='Valor de Venda')),
                ('lucro_previsto', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Valor de Venda - Custo Total Previsto', max_digits=15, verbose_name='Lucro Previsto')),
                ('margem_prevista_percentual', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Percentual de lucro sobre a venda', max_digits=5, verbose_name='Margem Prevista (%)')),
                ('percentual_uso_budget', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Percentual do budget já utilizado (gastos reais / custo previsto)', max_digits=5, verbose_name='Percentual Uso Budget (%)')),
                ('semaforo', models.CharField(choices=[('VERDE', 'Verde - Uso < 80%'), ('AMARELO', 'Amarelo - Uso 80-95%'), ('VERMELHO', 'Vermelho - Uso > 95%')], default='VERDE', editable=False, help_text='Indicador visual de status do budget', max_length=10, verbose_name='Semáforo')),
                ('bloqueado', models.BooleanField(default=False, help_text='Budget bloqueado por estourar limite (>95%)', verbose_name='Bloqueado')),
                ('data_inicio_prevista', models.DateField(blank=True, null=True, verbose_name='Data Início Prevista')),
                ('data_termino_prevista', models.DateField(blank=True, null=True, verbose_name='Data Término Prevista')),
                ('data_inicio_real', models.DateField(blank=True, null=True, verbose_name='Data Início Real')),
                ('data_termino_real', models.DateField(blank=True, null=True, verbose_name='Data Término Real')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets_projetos', to='usuarios.empresa', verbose_name='Empresa')),
                ('orcamento', models.ForeignKey(blank=True, help_text='Orçamento de vendas que originou este budget', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='vendas.orcamento', verbose_name='Orçamento')),
                ('projeto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget', to='projetos.projeto', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Budget de Projeto',
                'verbose_name_plural': 'Budgets de Projetos',
                'db_table': 'project_budgets',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='JustificativaBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('AUMENTO_ESCOPO', 'Aumento de Escopo'), ('ERRO_ORCAMENTO', 'Erro no Orçamento Original'), ('VARIACAO_PRECO', 'Variação de Preço de Insumos'), ('RETRABALHO', 'Retrabalho Necessário'), ('IMPREVISTO', 'Imprevisto na Obra'), ('SOLICITACAO_CLIENTE', 'Solicitação Extra do Cliente'), ('OUTROS', 'Outros Motivos')], max_length=30, verbose_name='Motivo')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('valor_adicional_necessario', models.DecimalField(decimal_places=2, help_text='Quanto a mais será necessário gastar', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Adicional Necessário')),
                ('documento_comprobatorio', models.FileField(blank=True, null=True, upload_to='budgets/justificativas/%Y/%m/', verbose_name='Documento Comprobatório')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente Análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Solicitação')),
                ('data_analise', models.DateTimeField(blank=True, null=True, verbose_name='Data Análise')),
                ('parecer', models.TextField(blank=True, verbose_name='Parecer')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas_analisadas', to=settings.AUTH_USER_MODEL, verbose_name='Analisado por')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='justificativas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='justificativas', to='financeiro.projectbudget', verbose_name='Budget')),
            ],
            options={
                'verbose_name': 'Justificativa de Budget',
                'verbose_name_plural': 'Justificativas de Budget',
                'db_table': 'justificativas_budget',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_despesa', models.CharField(choices=[('MATERIAL', 'Material'), ('MAO_OBRA', 'Mão de Obra'), ('COMBUSTIVEL', 'Combustível'), ('PEDAGIO', 'Pedágio'), ('ESTACIONAMENTO', 'Estacionamento'), ('ALIMENTACAO', 'Alimentação'), ('HOSPEDAGEM', 'Hospedagem'), ('RETRABALHO', 'Retrabalho'), ('DESPERDICIO', 'Desperdício de Material'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Despesa')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('km_rodado', models.DecimalField(blank=True, decimal_places=2, help_text='Quilometragem rodada (via GPS se disponível)', max_digits=10, null=True, verbose_name='KM Rodado')),
                ('litros_abastecidos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Litros Abastecidos')),
                ('horas_trabalhadas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Horas Trabalhadas')),
                ('recibo_imagem', models.ImageField(blank=True, help_text='Upload de foto/scan do recibo', null=True, upload_to='budgets/recibos/%Y/%m/', verbose_name='Imagem do Recibo')),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=50, verbose_name='Número da Nota Fiscal')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('local_descricao', models.CharField(blank=True, help_text='Endereço ou descrição do local', max_length=255, verbose_name='Descrição do Local')),
                ('data_despesa', models.DateField(default=datetime.date.today, verbose_name='Data da Despesa')),
                ('data_hora_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora Registro')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente Aprovação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('PAGO', 'Pago')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data Aprovação')),
                ('justificativa_rejeicao', models.TextField(blank=True, verbose_name='Justificativa Rejeição')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='financeiro.projectbudget', verbose_name='Budget')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_projetos', to='usuarios.empresa', verbose_name='Empresa')),
                ('funcionario', models.ForeignKey(blank=True, limit_choices_to={'funcionario': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas_trabalho', to='cadastros.pessoa', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Despesa de Projeto',
                'verbose_name_plural': 'Despesas de Projetos',
                'db_table': 'project_expenses',
                'ordering': ['-data_despesa', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AliquotaImposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_imposto', models.CharField(choices=[('ISS', 'ISS - Imposto Sobre Serviços'), ('ICMS', 'ICMS - Imposto sobre Circulação de Mercadorias'), ('PIS', 'PIS - Programa de Integração Social'), ('COFINS', 'COFINS - Contribuição para Financiamento da Seguridade Social'), ('IRPJ', 'IRPJ - Imposto de Renda Pessoa Jurídica'), ('CSLL', 'CSLL - Contribuição Social sobre Lucro Líquido'), ('IPI', 'IPI - Imposto sobre Produtos Industrializados'), ('INSS', 'INSS Patronal'), ('OUTROS', 'Outros Impostos')], max_length=20, verbose_name='Tipo de Imposto')),
                ('aliquota_percentual', models.DecimalField(decimal_places=2, help_text='Percentual do imposto (0 a 100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota (%)')),
                ('base_calculo', models.CharField(choices=[('FATURAMENTO', 'Faturamento Bruto'), ('LUCRO', 'Lucro Líquido'), ('CUSTO_MATERIAL', 'Custo de Material'), ('CUSTO_SERVICO', 'Custo de Serviço')], default='FATURAMENTO', max_length=20, verbose_name='Base de Cálculo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliquotas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliquotas_impostos', to='usuarios.empresa', verbose_name='Empresa')),
                ('regime_tributario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliquotas', to='financeiro.regimetributario', verbose_name='Regime Tributário')),
            ],
            options={
                'verbose_name': 'Alíquota de Imposto',
                'verbose_name_plural': 'Alíquotas de Impostos',
                'db_table': 'aliquotas_impostos',
                'ordering': ['regime_tributario', 'tipo_imposto'],
            },
        ),
        migrations.AddIndex(
            model_name='projectbudget',
            index=models.Index(fields=['status', 'semaforo'], name='project_bud_status_ec5d25_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbudget',
            index=models.Index(fields=['projeto'], name='project_bud_projeto_c88ced_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbudget',
            index=models.Index(fields=['orcamento'], name='project_bud_orcamen_c5dbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbudget',
            index=models.Index(fields=['bloqueado'], name='project_bud_bloquea_52c50f_idx'),
        ),
        migrations.AddIndex(
            model_name='justificativabudget',
            index=models.Index(fields=['budget', 'status'], name='justificati_budget__4a1e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='justificativabudget',
            index=models.Index(fields=['status'], name='justificati_status_7fa723_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['budget', 'status'], name='project_exp_budget__50a8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['tipo_despesa'], name='project_exp_tipo_de_5238c5_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['data_despesa'], name='project_exp_data_de_814a54_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['funcionario'], name='project_exp_funcion_6cad70_idx'),
        ),
        migrations.AddIndex(
            model_name='aliquotaimposto',
            index=models.Index(fields=['regime_tributario', 'ativo'], name='aliquotas_i_regime__a8bdfe_idx'),
        ),
        migrations.AddIndex(
            model_name='aliquotaimposto',
            index=models.Index(fields=['tipo_imposto'], name='aliquotas_i_tipo_im_591253_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aliquotaimposto',
            unique_together={('empresa', 'regime_tributario', 'tipo_imposto')},
        ),
    ]
