# Generated by Django 6.0 on 2026-01-12 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_regimetributario_projectbudget_justificativabudget_and_more'),
        ('usuarios', '0004_empresa_regime_tributario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aliquotaimposto',
            name='data_fim_vigencia',
            field=models.DateField(blank=True, help_text='Data em que esta alíquota deixou de valer (preenchido automaticamente ao mudar regime)', null=True, verbose_name='Data Fim Vigência'),
        ),
        migrations.AddField(
            model_name='aliquotaimposto',
            name='data_inicio_vigencia',
            field=models.DateField(blank=True, help_text='Data em que esta alíquota começou a valer', null=True, verbose_name='Data Início Vigência'),
        ),
        migrations.CreateModel(
            name='HistoricoRegimeEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Data em que o regime começou a valer', verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Data em que o regime deixou de valer', null=True, verbose_name='Data de Término')),
                ('ativo', models.BooleanField(default=True, help_text='Apenas um regime pode estar ativo por vez', verbose_name='Regime Ativo')),
                ('motivo_mudanca', models.TextField(blank=True, help_text='Justificativa para mudança de regime (ex: crescimento, redução de faturamento, etc)', verbose_name='Motivo da Mudança')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudancas_regime_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_regimes', to='usuarios.empresa', verbose_name='Empresa')),
                ('regime_tributario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_uso', to='financeiro.regimetributario', verbose_name='Regime Tributário')),
            ],
            options={
                'verbose_name': 'Histórico de Regime',
                'verbose_name_plural': 'Históricos de Regimes',
                'db_table': 'historico_regime_empresa',
                'ordering': ['-data_inicio'],
                'indexes': [models.Index(fields=['empresa', 'ativo'], name='historico_r_empresa_1380c6_idx'), models.Index(fields=['data_inicio', 'data_fim'], name='historico_r_data_in_c49b50_idx')],
            },
        ),
    ]
