# Generated by Django 6.0 on 2026-02-24 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_aliquotaimposto_data_fim_vigencia_and_more'),
        ('projetos', '0015_diarioobra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocusto',
            name='projeto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centro_custo', to='projetos.projeto', verbose_name='Projeto Relacionado'),
        ),
    ]
