# Generated by Django 6.0 on 2026-02-24 01:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0007_rename_pessoa_emp_ativo_idx_cadastros_p_empresa_b3572f_idx_and_more'),
        ('projetos', '0017_orcamento_data_aprovacao_orcamento_descricao_and_more'),
        ('usuarios', '0005_backupconfig_backupbancodados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaFunil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0)),
                ('cor', models.CharField(default='#3498db', help_text='Cor em hexadecimal (#RRGGBB)', max_length=7)),
                ('is_final', models.BooleanField(default=False, help_text='Etapa final do funil')),
                ('tipo_final', models.CharField(choices=[('ganho', 'Ganho (Deal fechado)'), ('perdido', 'Perdido (Deal não fechado)'), ('none', 'Não é final')], default='none', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etapa do Funil',
                'verbose_name_plural': 'Etapas do Funil',
                'ordering': ['pipeline', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(help_text='Nome do contato principal', max_length=200)),
                ('empresa_contato', models.CharField(blank=True, help_text='Nome da empresa do lead', max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('titulo', models.CharField(help_text='Título/resumo da oportunidade', max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('site', 'Site'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('indicacao', 'Indicação'), ('rede_social', 'Rede Social'), ('visita', 'Visita Presencial'), ('evento', 'Evento'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('ganho', 'Ganho'), ('perdido', 'Perdido'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_prevista_fechamento', models.DateField(blank=True, null=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente cadastrado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='cadastros.pessoa')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='usuarios.empresa')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='crm.etapafunil')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidade_origem', to='projetos.orcamento')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidade_origem', to='projetos.projeto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnexoOportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='crm/anexos/%Y/%m/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='crm.oportunidade')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('padrao', models.BooleanField(default=False, help_text='Pipeline padrão para novos cards')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='usuarios.empresa')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['empresa', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='etapafunil',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='crm.pipeline'),
        ),
        migrations.CreateModel(
            name='HistoricoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('etapa_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_saida', to='crm.etapafunil')),
                ('etapa_para', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_entrada', to='crm.etapafunil')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_etapas', to='crm.oportunidade')),
            ],
            options={
                'verbose_name': 'Histórico de Etapa',
                'verbose_name_plural': 'Históricos de Etapas',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['oportunidade', '-data_hora'], name='crm_histori_oportun_e2d1cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='AtividadeCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nota', 'Nota/Observação'), ('ligacao', 'Ligação'), ('email', 'E-mail'), ('reuniao', 'Reunião'), ('whatsapp', 'WhatsApp'), ('visita', 'Visita'), ('proposta', 'Proposta Enviada'), ('negociacao', 'Negociação'), ('outro', 'Outro')], default='nota', max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField()),
                ('data_atividade', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='crm.oportunidade')),
            ],
            options={
                'verbose_name': 'Atividade CRM',
                'verbose_name_plural': 'Atividades CRM',
                'ordering': ['-data_atividade'],
                'indexes': [models.Index(fields=['oportunidade', '-data_atividade'], name='crm_ativida_oportun_a94721_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertaRetorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=10)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_concluidos', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_criados', to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='crm.oportunidade')),
            ],
            options={
                'verbose_name': 'Alerta/Tarefa',
                'verbose_name_plural': 'Alertas/Tarefas',
                'ordering': ['data_hora', '-prioridade'],
                'indexes': [models.Index(fields=['oportunidade', 'status'], name='crm_alertar_oportun_239c46_idx'), models.Index(fields=['data_hora', 'status'], name='crm_alertar_data_ho_b524a3_idx'), models.Index(fields=['criado_por', 'status'], name='crm_alertar_criado__409926_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['empresa', 'ativo'], name='crm_pipelin_empresa_94f7ae_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['empresa', 'etapa', 'responsavel'], name='crm_oportun_empresa_b13bad_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['empresa', 'status'], name='crm_oportun_empresa_013e44_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['responsavel', 'status'], name='crm_oportun_respons_82d715_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['updated_at'], name='crm_oportun_updated_3074a1_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['data_entrada'], name='crm_oportun_data_en_ea3b65_idx'),
        ),
        migrations.AddIndex(
            model_name='etapafunil',
            index=models.Index(fields=['pipeline', 'ordem'], name='crm_etapafu_pipelin_3e410c_idx'),
        ),
        migrations.AddIndex(
            model_name='etapafunil',
            index=models.Index(fields=['pipeline', 'ativo'], name='crm_etapafu_pipelin_c0a8c3_idx'),
        ),
    ]
