# Generated by Django 6.0 on 2026-02-24 17:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('usuarios', '0005_backupconfig_backupbancodados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='numero_projeto',
            field=models.CharField(blank=True, help_text='Número do projeto quando convertido', max_length=50),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='probabilidade_conversao',
            field=models.IntegerField(default=50, help_text='Probabilidade de conversão (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='valor_fechado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor real quando fechado', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='valor_previsto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor previsto para este negócio', max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='EtapaFunilConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade_padrao', models.IntegerField(default=50, help_text='Probabilidade padrão de conversão nesta etapa (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sla_dias', models.IntegerField(default=7, help_text='Tempo médio esperado nesta etapa (em dias)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etapa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='crm.etapafunil')),
            ],
            options={
                'verbose_name': 'Configuração de Etapa',
                'verbose_name_plural': 'Configurações de Etapas',
            },
        ),
        migrations.CreateModel(
            name='MetaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='Mês (1-12)')),
                ('ano', models.IntegerField(help_text='Ano')),
                ('meta_valor', models.DecimalField(decimal_places=2, help_text='Meta de valor a ser fechado no mês', max_digits=15)),
                ('meta_quantidade', models.IntegerField(default=0, help_text='Meta de quantidade de negócios a fechar')),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_vendedores', to='usuarios.empresa')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_vendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de Vendedor',
                'verbose_name_plural': 'Metas de Vendedores',
                'ordering': ['-ano', '-mes', 'vendedor__first_name'],
                'indexes': [models.Index(fields=['empresa', 'vendedor', '-ano', '-mes'], name='crm_metaven_empresa_44d299_idx'), models.Index(fields=['empresa', '-ano', '-mes'], name='crm_metaven_empresa_735178_idx')],
                'unique_together': {('empresa', 'vendedor', 'mes', 'ano')},
            },
        ),
    ]
